/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as RecipesRecipeSlugRouteImport } from './routes/recipes.$recipeSlug'
import { Route as GalleryNewbornsRouteImport } from './routes/gallery.newborns'
import { Route as GalleryMaternityRouteImport } from './routes/gallery.maternity'
import { Route as GalleryFlowersRouteImport } from './routes/gallery.flowers'
import { Route as GalleryFloridaBirdingRouteImport } from './routes/gallery.florida-birding'
import { Route as GalleryBoatsRouteImport } from './routes/gallery.boats'
import { Route as BlogCategoryIndexRouteImport } from './routes/blog.$category.index'
import { Route as BlogCategoryPostSlugRouteImport } from './routes/blog.$category.$postSlug'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const RecipesRecipeSlugRoute = RecipesRecipeSlugRouteImport.update({
  id: '/recipes/$recipeSlug',
  path: '/recipes/$recipeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryNewbornsRoute = GalleryNewbornsRouteImport.update({
  id: '/gallery/newborns',
  path: '/gallery/newborns',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryMaternityRoute = GalleryMaternityRouteImport.update({
  id: '/gallery/maternity',
  path: '/gallery/maternity',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryFlowersRoute = GalleryFlowersRouteImport.update({
  id: '/gallery/flowers',
  path: '/gallery/flowers',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryFloridaBirdingRoute = GalleryFloridaBirdingRouteImport.update({
  id: '/gallery/florida-birding',
  path: '/gallery/florida-birding',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryBoatsRoute = GalleryBoatsRouteImport.update({
  id: '/gallery/boats',
  path: '/gallery/boats',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoryIndexRoute = BlogCategoryIndexRouteImport.update({
  id: '/$category/',
  path: '/$category/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogCategoryPostSlugRoute = BlogCategoryPostSlugRouteImport.update({
  id: '/$category/$postSlug',
  path: '/$category/$postSlug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery/boats': typeof GalleryBoatsRoute
  '/gallery/florida-birding': typeof GalleryFloridaBirdingRoute
  '/gallery/flowers': typeof GalleryFlowersRoute
  '/gallery/maternity': typeof GalleryMaternityRoute
  '/gallery/newborns': typeof GalleryNewbornsRoute
  '/recipes/$recipeSlug': typeof RecipesRecipeSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/$category/$postSlug': typeof BlogCategoryPostSlugRoute
  '/blog/$category/': typeof BlogCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery/boats': typeof GalleryBoatsRoute
  '/gallery/florida-birding': typeof GalleryFloridaBirdingRoute
  '/gallery/flowers': typeof GalleryFlowersRoute
  '/gallery/maternity': typeof GalleryMaternityRoute
  '/gallery/newborns': typeof GalleryNewbornsRoute
  '/recipes/$recipeSlug': typeof RecipesRecipeSlugRoute
  '/blog': typeof BlogIndexRoute
  '/blog/$category/$postSlug': typeof BlogCategoryPostSlugRoute
  '/blog/$category': typeof BlogCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery/boats': typeof GalleryBoatsRoute
  '/gallery/florida-birding': typeof GalleryFloridaBirdingRoute
  '/gallery/flowers': typeof GalleryFlowersRoute
  '/gallery/maternity': typeof GalleryMaternityRoute
  '/gallery/newborns': typeof GalleryNewbornsRoute
  '/recipes/$recipeSlug': typeof RecipesRecipeSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/$category/$postSlug': typeof BlogCategoryPostSlugRoute
  '/blog/$category/': typeof BlogCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery/boats'
    | '/gallery/florida-birding'
    | '/gallery/flowers'
    | '/gallery/maternity'
    | '/gallery/newborns'
    | '/recipes/$recipeSlug'
    | '/blog/'
    | '/blog/$category/$postSlug'
    | '/blog/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery/boats'
    | '/gallery/florida-birding'
    | '/gallery/flowers'
    | '/gallery/maternity'
    | '/gallery/newborns'
    | '/recipes/$recipeSlug'
    | '/blog'
    | '/blog/$category/$postSlug'
    | '/blog/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery/boats'
    | '/gallery/florida-birding'
    | '/gallery/flowers'
    | '/gallery/maternity'
    | '/gallery/newborns'
    | '/recipes/$recipeSlug'
    | '/blog/'
    | '/blog/$category/$postSlug'
    | '/blog/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryBoatsRoute: typeof GalleryBoatsRoute
  GalleryFloridaBirdingRoute: typeof GalleryFloridaBirdingRoute
  GalleryFlowersRoute: typeof GalleryFlowersRoute
  GalleryMaternityRoute: typeof GalleryMaternityRoute
  GalleryNewbornsRoute: typeof GalleryNewbornsRoute
  RecipesRecipeSlugRoute: typeof RecipesRecipeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/recipes/$recipeSlug': {
      id: '/recipes/$recipeSlug'
      path: '/recipes/$recipeSlug'
      fullPath: '/recipes/$recipeSlug'
      preLoaderRoute: typeof RecipesRecipeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/newborns': {
      id: '/gallery/newborns'
      path: '/gallery/newborns'
      fullPath: '/gallery/newborns'
      preLoaderRoute: typeof GalleryNewbornsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/maternity': {
      id: '/gallery/maternity'
      path: '/gallery/maternity'
      fullPath: '/gallery/maternity'
      preLoaderRoute: typeof GalleryMaternityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/flowers': {
      id: '/gallery/flowers'
      path: '/gallery/flowers'
      fullPath: '/gallery/flowers'
      preLoaderRoute: typeof GalleryFlowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/florida-birding': {
      id: '/gallery/florida-birding'
      path: '/gallery/florida-birding'
      fullPath: '/gallery/florida-birding'
      preLoaderRoute: typeof GalleryFloridaBirdingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/boats': {
      id: '/gallery/boats'
      path: '/gallery/boats'
      fullPath: '/gallery/boats'
      preLoaderRoute: typeof GalleryBoatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$category/': {
      id: '/blog/$category/'
      path: '/$category'
      fullPath: '/blog/$category/'
      preLoaderRoute: typeof BlogCategoryIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$category/$postSlug': {
      id: '/blog/$category/$postSlug'
      path: '/$category/$postSlug'
      fullPath: '/blog/$category/$postSlug'
      preLoaderRoute: typeof BlogCategoryPostSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogIndexRoute: typeof BlogIndexRoute
  BlogCategoryPostSlugRoute: typeof BlogCategoryPostSlugRoute
  BlogCategoryIndexRoute: typeof BlogCategoryIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIndexRoute: BlogIndexRoute,
  BlogCategoryPostSlugRoute: BlogCategoryPostSlugRoute,
  BlogCategoryIndexRoute: BlogCategoryIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryBoatsRoute: GalleryBoatsRoute,
  GalleryFloridaBirdingRoute: GalleryFloridaBirdingRoute,
  GalleryFlowersRoute: GalleryFlowersRoute,
  GalleryMaternityRoute: GalleryMaternityRoute,
  GalleryNewbornsRoute: GalleryNewbornsRoute,
  RecipesRecipeSlugRoute: RecipesRecipeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
