/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesShrimpPoboyRouteImport } from './routes/recipes.shrimp-poboy'
import { Route as GalleryNewbornsRouteImport } from './routes/gallery.newborns'
import { Route as GalleryMaternityRouteImport } from './routes/gallery.maternity'
import { Route as GalleryFlowersRouteImport } from './routes/gallery.flowers'
import { Route as GalleryFloridaBirdingRouteImport } from './routes/gallery.florida-birding'
import { Route as GalleryBoatsRouteImport } from './routes/gallery.boats'
import { Route as BlogCategoryRouteImport } from './routes/blog.$category'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesShrimpPoboyRoute = RecipesShrimpPoboyRouteImport.update({
  id: '/recipes/shrimp-poboy',
  path: '/recipes/shrimp-poboy',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryNewbornsRoute = GalleryNewbornsRouteImport.update({
  id: '/gallery/newborns',
  path: '/gallery/newborns',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryMaternityRoute = GalleryMaternityRouteImport.update({
  id: '/gallery/maternity',
  path: '/gallery/maternity',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryFlowersRoute = GalleryFlowersRouteImport.update({
  id: '/gallery/flowers',
  path: '/gallery/flowers',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryFloridaBirdingRoute = GalleryFloridaBirdingRouteImport.update({
  id: '/gallery/florida-birding',
  path: '/gallery/florida-birding',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryBoatsRoute = GalleryBoatsRouteImport.update({
  id: '/gallery/boats',
  path: '/gallery/boats',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoryRoute = BlogCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/blog/$category': typeof BlogCategoryRoute
  '/gallery/boats': typeof GalleryBoatsRoute
  '/gallery/florida-birding': typeof GalleryFloridaBirdingRoute
  '/gallery/flowers': typeof GalleryFlowersRoute
  '/gallery/maternity': typeof GalleryMaternityRoute
  '/gallery/newborns': typeof GalleryNewbornsRoute
  '/recipes/shrimp-poboy': typeof RecipesShrimpPoboyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/blog/$category': typeof BlogCategoryRoute
  '/gallery/boats': typeof GalleryBoatsRoute
  '/gallery/florida-birding': typeof GalleryFloridaBirdingRoute
  '/gallery/flowers': typeof GalleryFlowersRoute
  '/gallery/maternity': typeof GalleryMaternityRoute
  '/gallery/newborns': typeof GalleryNewbornsRoute
  '/recipes/shrimp-poboy': typeof RecipesShrimpPoboyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/blog/$category': typeof BlogCategoryRoute
  '/gallery/boats': typeof GalleryBoatsRoute
  '/gallery/florida-birding': typeof GalleryFloridaBirdingRoute
  '/gallery/flowers': typeof GalleryFlowersRoute
  '/gallery/maternity': typeof GalleryMaternityRoute
  '/gallery/newborns': typeof GalleryNewbornsRoute
  '/recipes/shrimp-poboy': typeof RecipesShrimpPoboyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/blog/$category'
    | '/gallery/boats'
    | '/gallery/florida-birding'
    | '/gallery/flowers'
    | '/gallery/maternity'
    | '/gallery/newborns'
    | '/recipes/shrimp-poboy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/blog/$category'
    | '/gallery/boats'
    | '/gallery/florida-birding'
    | '/gallery/flowers'
    | '/gallery/maternity'
    | '/gallery/newborns'
    | '/recipes/shrimp-poboy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/blog/$category'
    | '/gallery/boats'
    | '/gallery/florida-birding'
    | '/gallery/flowers'
    | '/gallery/maternity'
    | '/gallery/newborns'
    | '/recipes/shrimp-poboy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryBoatsRoute: typeof GalleryBoatsRoute
  GalleryFloridaBirdingRoute: typeof GalleryFloridaBirdingRoute
  GalleryFlowersRoute: typeof GalleryFlowersRoute
  GalleryMaternityRoute: typeof GalleryMaternityRoute
  GalleryNewbornsRoute: typeof GalleryNewbornsRoute
  RecipesShrimpPoboyRoute: typeof RecipesShrimpPoboyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/shrimp-poboy': {
      id: '/recipes/shrimp-poboy'
      path: '/recipes/shrimp-poboy'
      fullPath: '/recipes/shrimp-poboy'
      preLoaderRoute: typeof RecipesShrimpPoboyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/newborns': {
      id: '/gallery/newborns'
      path: '/gallery/newborns'
      fullPath: '/gallery/newborns'
      preLoaderRoute: typeof GalleryNewbornsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/maternity': {
      id: '/gallery/maternity'
      path: '/gallery/maternity'
      fullPath: '/gallery/maternity'
      preLoaderRoute: typeof GalleryMaternityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/flowers': {
      id: '/gallery/flowers'
      path: '/gallery/flowers'
      fullPath: '/gallery/flowers'
      preLoaderRoute: typeof GalleryFlowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/florida-birding': {
      id: '/gallery/florida-birding'
      path: '/gallery/florida-birding'
      fullPath: '/gallery/florida-birding'
      preLoaderRoute: typeof GalleryFloridaBirdingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/boats': {
      id: '/gallery/boats'
      path: '/gallery/boats'
      fullPath: '/gallery/boats'
      preLoaderRoute: typeof GalleryBoatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$category': {
      id: '/blog/$category'
      path: '/$category'
      fullPath: '/blog/$category'
      preLoaderRoute: typeof BlogCategoryRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogCategoryRoute: typeof BlogCategoryRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogCategoryRoute: BlogCategoryRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryBoatsRoute: GalleryBoatsRoute,
  GalleryFloridaBirdingRoute: GalleryFloridaBirdingRoute,
  GalleryFlowersRoute: GalleryFlowersRoute,
  GalleryMaternityRoute: GalleryMaternityRoute,
  GalleryNewbornsRoute: GalleryNewbornsRoute,
  RecipesShrimpPoboyRoute: RecipesShrimpPoboyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
